version: "2.0"
services:
  web:
    image: ouououo/tieba-cloud-sign
    environment:
      - PUID=1000 # 可修改为你想以什么用户运行caddy，该用户的UID
      - PGID=1000 # 可修改为你想以什么用户运行caddy，该用户的UID
      - DB_HOST=db:3306
      - DB_USER=root
      - DB_PASSWD=janejane123456 # 数据库密码
      - DB_NAME=tiebacloud # 数据库名
      - CSRF=true
      # - TC_AUTO_CREATE_INSTALL_LOCK=true # 如果希望自动创建install.lock请解除此注释
    volumes:
      - /docker/ssl:/etc/caddy/ssl
      # - ./install.lock:/var/www/setup/install.lock  # 在当前目录下自行新建文件install.lock，内容为：1
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db

  db:
    image: agrozyme/mariadb #如若此镜像在你的平台上不可用，可以自行在docker hub上搜索你平台可用的mariadb镜像
    environment:
      - MYSQL_DATABASE=tiebacloud
      - MYSQL_ROOT_PASSWORD=janejane123456
    volumes:
      - /docker/tb/mysql:/var/lib/mysql
